apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    k8s-app: maria-app
  name: my-volume-app
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi